global:
  OPEN_AI_API_KEY_FILE: "~/default_openai_api_key.txt"
  persistent_log: true  # Set to true for persistent logging

operations:
  - name: Summarize Text
    function: chatgpt
    parameters:
      prompt: "{INCLUDE: summarize.txt}"
      model: "gpt-3.5-turbo"
      max_tokens: 150
      temperature: 0.5

  - name: Translate to Russian
    function: chatgpt
    parameters:
      prompt: "{INCLUDE: translate_into_russian.txt}"
      model: "gpt-3.5-turbo"
      max_tokens: 200
      temperature: 0.7

  - name: Wikipedia Search
    function: wiki
    parameters:
      sentences: 2  # Optional: Number of sentences to return from the summary

  - name: Thesaurus Lookup
    function: thesaurus
    parameters:
      part_of_speech: null  # Optional, not used in this version